<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netstandard2.1;net6.0;net7.0;net8.0;net9.0;net6.0-windows;net7.0-windows;net8.0-windows;net9.0-windows;netcoreapp2.2;netcoreapp3.1</TargetFrameworks>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>QingYi.Crypto</Title>
    <Version>3.0.0-pre.1</Version>
    <Authors>QingYi-Studio</Authors>
    <Description>A simple library that can be quickly encrypted and decrypted, based on native C#.
For business please send Issue or contact us directly.</Description>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/QingYi-Studio/QingYi.Cryption</RepositoryUrl>
    <PackageProjectUrl>https://github.com/QingYi-Studio/QingYi.Cryption</PackageProjectUrl>
    <PackageTags>Crypto;DES;XOR;Morse;MessageDigest;TripleDES;AES;SHA</PackageTags>
    <PackageIcon>use.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageReleaseNotes>Rewrite some method.</PackageReleaseNotes>
    <ProduceReferenceAssembly>True</ProduceReferenceAssembly>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <Copyright>GPL-3.0</Copyright>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|netstandard2.0|AnyCPU'">
    <NoWarn>1701;1702;1903</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|netstandard2.1|AnyCPU'">
    <NoWarn>1701;1702;1903</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net6.0|AnyCPU'">
    <NoWarn>1701;1702;1903</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net7.0|AnyCPU'">
    <NoWarn>1701;1702;1903</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net8.0|AnyCPU'">
    <NoWarn>1701;1702;1903</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net9.0|AnyCPU'">
    <NoWarn>1701;1702;1903</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net6.0-windows|AnyCPU'">
    <NoWarn>1701;1702;1903</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net7.0-windows|AnyCPU'">
    <NoWarn>1701;1702;1903</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net8.0-windows|AnyCPU'">
    <NoWarn>1701;1702;1903</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net9.0-windows|AnyCPU'">
    <NoWarn>1701;1702;1903</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|netcoreapp2.2|AnyCPU'">
    <NoWarn>1701;1702;1903</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|netcoreapp3.1|AnyCPU'">
    <NoWarn>1701;1702;1903</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|netstandard2.0|AnyCPU'">
    <NoWarn>1701;1702;1903</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|netstandard2.1|AnyCPU'">
    <NoWarn>1701;1702;1903</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net6.0|AnyCPU'">
    <NoWarn>1701;1702;1903</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net7.0|AnyCPU'">
    <NoWarn>1701;1702;1903</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0|AnyCPU'">
    <NoWarn>1701;1702;1903</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net9.0|AnyCPU'">
    <NoWarn>1701;1702;1903</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net6.0-windows|AnyCPU'">
    <NoWarn>1701;1702;1903</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net7.0-windows|AnyCPU'">
    <NoWarn>1701;1702;1903</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0-windows|AnyCPU'">
    <NoWarn>1701;1702;1903</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net9.0-windows|AnyCPU'">
    <NoWarn>1701;1702;1903</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|netcoreapp2.2|AnyCPU'">
    <NoWarn>1701;1702;1903</NoWarn>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|netcoreapp3.1|AnyCPU'">
    <NoWarn>1701;1702;1903</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="AES\CFB\**" />
    <EmbeddedResource Remove="AES\CFB\**" />
    <None Remove="AES\CFB\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="AES\mode_diff.md" />
    <None Remove="DES\mode_diff.md" />
    <None Remove="Morse\custom-dictionary-example.md" />
    <None Remove="readme.md" />
    <None Remove="use.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="AES\mode_diff.md" />
    <Content Include="DES\mode_diff.md">
      <Pack>True</Pack>
    </Content>
    <Content Include="Morse\custom-dictionary-example.md" />
    <Content Include="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </Content>
    <Content Include="use.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="RC\V2\" />
    <Folder Include="RC\V4\" />
    <Folder Include="RC\V5\" />
    <Folder Include="RC\V6\" />
    <Folder Include="SecureHashAlgorithm\SHA2\" />
    <Folder Include="SecureHashAlgorithm\SHA3\" />
    <Folder Include="SM\V1\" />
    <Folder Include="SM\V3\" />
    <Folder Include="SM\V4\" />
    <Folder Include="SM\V7\" />
    <Folder Include="SM\V9\" />
    <Folder Include="SM\ZUC\" />
    <Folder Include="BlowFish\" />
    <Folder Include="Rabbit\" />
    <Folder Include="RSA\" />
    <Folder Include="HMAC\" />
    <Folder Include="OMAC\" />
    <Folder Include="CBC-MAC\" />
    <Folder Include="SM\V2\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
</Project>
